name: sup

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v1
      - name: Cache Node Template
        uses: actions/cache@v1
        env:
          cache-name: substrate-cache
        with:
          path: ./target
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*/Cargo.lock') }}
      - name: Build
        run: cargo build -vv --release
      - name: Run tests
        run: cargo test -vv --release
      - name: Build template
        run: |
          ./target/release/sup new target/supnode
          cd target/supnode
          cargo build -vv --release
      - name: Upgrade template
        run: |
          ./target/release/sup upgrade -t v2.0.0-rc1
          cargo build -vv --release
          
